name: Auto approve and merge PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Approve PR
        if: ${{ github.head_ref == 'auto-update-exchange-rates' }}
        uses: hmarr/auto-approve-action@v3
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Reviewed by a 🤖"
