name: Auto merge PR

on:
  pull_request:
    types:
      - labeled
      - opened
      - edited
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate token 
        if: ${{ github.head_ref == 'auto-update-exchange-rates' }}
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Auto merge PR for exchange rate
        if: ${{ github.head_ref == 'auto-update-exchange-rates' }}
        env:
          BASE_BRANCHES: main
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          MERGE_LABELS: automated
          MERGE_COMMIT_MESSAGE: "🤖 PR was merged automatically"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "20000"
          MERGE_REQUIRED_APPROVALS: "1"
          MERGE_DELETE_BRANCH: true
        uses: "pascalgn/automerge-action@v0.15.5"