name: Auto approve

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Print head branch on PR
        run: |
          echo $GITHUB_HEAD_REF
      - name: Auto Approve PR
        # if: $GITHUB_HEAD_REF == 'auto-update-exchange-rates'
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR"