name: Auto approve

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Print head branch on PR
        run: |
          echo ${{ github.event.pull_request.head_ref }}
      - name: Auto Approve PR
        if: ${{ github.event.pull_request.head_ref }} == 'auto-update-exchange-rates'
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR"