name: Auto approve and merge PR

on:
  pull_request:
    branches:
      - main
  check_suite:
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate token 
        if: ${{ github.head_ref == 'auto-update-exchange-rates' }}
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Auto approve PR for exchange rate
        if: ${{ github.head_ref == 'auto-update-exchange-rates' }}
        uses: hmarr/auto-approve-action@v3
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Reviewed by a 🤖"

      - name: Auto merge PR for exchange rate
        if: ${{ github.head_ref == 'auto-update-exchange-rates' }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          MERGE_LABELS: automated
          MERGE_COMMIT_MESSAGE: "🤖 PR was merged automatically"
          BASE_BRANCHES: main
        uses: "pascalgn/automerge-action@v0.15.5"
        