name: Auto approve

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Approve PR
        if: ${{ github.event.pull_request.head_ref }} == 'auto-update-exchange-rates'
        uses: hmarr/auto-approve-action@v3
        run: |
          echo "Auto approving PR with base ref to ${{ github.event.pull_request.base_ref }} and head ref to ${{ github.event.pull_request.head_ref }}" 
        review-message: "Auto approved automated PR"