name: Dummy Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Name github branch
        run: |
          echo ${{ github.ref }}
          echo $(git branch --show-current) 

      - name: Print github event
        run : |
          more $GITHUB_EVENT_PATH

      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash
