name: Exchange Rates

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Fetch exchange rates
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p resources
          cd ./resources 
          echo "This was added at $(date)" >> append-log.logs
      
      - name: Get token 
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with: 
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update exchange rates
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: auto-update-exchange-rates
          labels: automated
          base: main
          title: "🤖 Auto Update Exchange Rates"
          body: |
            Update report 🤖!!
            - This is an auto generating PR  
            - This PR updates exchange rates
          delete-branch: true
